type: object
title: Security
description: >
  Object for cluster security features.
properties:
  containerImage:
    type: object
    properties:
      approvedImages:
        type: array
        description: Set a permitted list of repositories for container images.
        items:
          type: string
          example:
            - "*.ecr.*.amazonaws.com/*"
            - "docker.*"
