type: object
title: Expression config
required:
  - name
  - expression
properties:
  name:
    type: string
    description: |
      The expression name.
    example: "e1"
  expression:
    type: string
    description: |
      An expression consisting of the metric names listed in the 'metrics' array.
    example: "metric1+10"

