type: object
properties:
  roll:
    type: object
    title: Role
    properties:
      status:
        type: string
        title: Status
        example: STOPPED
        description: >
          Set the status of the group to `STOPPED"
