in: query
name: submissionSource
required: false
description: >
  Optionally filter on the submission source of the Spark application
schema:
  $ref: "../../schemas/oceanSparkApplicationSubmissionSource.yaml"
