type: object
required:
  - address
title: Ocean CD Verification Provider Prometheus
properties:
  address:
    type: string
    description: The address which the Prometheus server available on
    example: http://localhost:9090