type: object
description: >
  The configuration template used to create the Spark application.
properties:
  id:
    type: string
    description: >
      The ID of the configuration template.
    example: "string"
  displayName:
    type: string
    description: >
      The display name of the configuration template.
    example: "string"