type: object
title: Ocean CD Rollout Spec Traffic ALB Stickiness config
description: >
  Allows to specify further settings on the ForwardConfig
properties:
  enabled:
    type: boolean
    description: Enables the load balancer to bind a user's session to a specific target.
    example: true
  durationSeconds:
    type: integer
    description: Defines how long the load balancer should consistently route the user's request to the same target
    example: 3600