type: object
title: Ocean CD Spot Deployment Selector
description: Represents the SpotDeployment selector
required:
  - clusterId
  - namespace
  - name
properties:
  clusterId:
    type: string
    description: Ocean CD cluster identifier for the references SpotDeployment
    example: aws-cluster
  namespace:
    type: string
    description: The namespace where the SpotDeployment resource exists
    example: us-region
  name:
    type: string
    example: us-app
    description: The name of the SpotDeployment resource