type: object
title: Cluster Configuration Object
description: >
  Information about the configurations file that will be used in the EMR cluster.
  for more information please see [Advanced - Using Bootstrap And Configuration Files](https://help.spot.io/elastigroup-for-aws/services-integrations/elastic-mapreduce/import-an-emr-cluster/advanced/)
properties:
  file:
    type: object
    description: Location and name of the configurations file that will be used in the EMR cluster.
    properties:
      bucket:
        type: string
        description: The S3 bucket where the file is stored.
        example: "emr-test"
      key:
        type: string
        description: The S3 Bucket key of the file.
        example: "MyFile.json"
