get:
  summary: Elastigroup Azure Deployment - Describe Deployment
  description: >
    Describe a single deployment for an Azure Elastigroup
  operationId: elastigroupAzureDeploymentDescribe
  tags:
    - Elastigroup Azure Low Priority VMs Deployment
  parameters:
    - $ref: "../../../../../commons/parameters/accountId.yaml"
    - $ref: "../../../commons/parameters/groupId.yaml"
    - $ref: "../../../commons/parameters/deploymentId.yaml"
  responses:
    200:
      $ref: "../responses/deployment.yaml"
    400:
      description: "Bad Request"

put:
  summary: Elastigroup Azure Deployment - Stop Deployment
  description: >
    Stop a deployment
  operationId: elastigroupAzureDeploymentStop
  tags:
    - Elastigroup Azure Low Priority VMs Deployment
  parameters:
    - $ref: "../../../../../commons/parameters/accountId.yaml"
    - $ref: "../../../commons/parameters/groupId.yaml"
    - $ref: "../../../commons/parameters/deploymentId.yaml"
  requestBody:
    required: true
    content:
      application/json:
        schema:
          allOf:
            - type: object
              properties:
                roll:
                  type: object
                  properties:
                    status:
                      type: string
                      default: "ROLL_STOPPED"
                      description: |
                        set the status of the roll to “ROLL_STOPPED”
  responses:
    200:
      $ref: "../../../../../commons/responses/spotinstResponseWrapper.yaml"
    400:
      description: "Bad Request"

