put:
  summary: "Stop Deployment"
  description:
    Stop an existing deployment
  operationId: "elastigroupAwsStopDeployment"
  tags:
    - "Elastigroup AWS Deployment"
  parameters:
    - $ref: "../../../../commons/parameters/groupId.yaml"
    - in: "path"
      name: "rollId"
      example: "sbgd-9876"
      description: >
        The deployment ID you want to stop
      schema:
        type: "string"
      required: true
    - in: "query"
      name: "accountId"
      example: "act-123abc"
      description: >
        ID of the account associated with your token
      schema:
        type: "string"
      required: false
  requestBody:
    required: true
    content:
      application/json:
        schema:
          allOf:
            - $ref: "../schemas/stop-deployment.yaml"
  responses:
    200:
      $ref: "../responses/group-deployment-stop.yaml"
    400:
      description: "Bad Request"

get:
  summary: "Deploy Status"
  description:
    Get status of a specific deployment
  operationId: "elastigroupAwsDeployStatus"
  tags:
    - "Elastigroup AWS Deployment"
  parameters:
    - $ref: "../../../../commons/parameters/groupId.yaml"
    - in: "path"
      name: "rollId"
      example: "sbgd-9876"
      description: >
        The deployment ID you want to query
      schema:
        type: "string"
      required: true
    - in: "query"
      name: "accountId"
      example: "act-123abc"
      description: >
        ID of the account associated with your token
      schema:
        type: "string"
      required: false
  responses:
    200:
      $ref: "../responses/elastigroup-deploy-status.yaml"
    400:
      description: "Bad Request"


