get:
  summary: "Group's Deployments Status"
  description:
    Get list of all the deployments of a specific Elastigroup and their status
  operationId: "elastigroupAwsDeploymentsStatus"
  tags:
    - "Elastigroup AWS"
  parameters:
    - $ref: "../../../../commons/parameters/groupId.yaml"
    - in: "query"
      name: "accountId"
      example: "act-123abc"
      description: >
        ID of the account associated with your token
      schema:
        type: "string"
      required: false
    - in: "query"
      name: "limit"
      example: "5"
      description: >
        Limits results
      schema:
        type: "integer"
      required: false
    - in: "query"
      name: "sort"
      example: "createdAt:ASC"
      description: >
        Field to sort by the results
        Default: createdAt:DESC
      schema:
        type: "string"
      required: false

  responses:
    200:
      $ref: "../responses/elastigroup-deployment-status.yaml"
    400:
      description: "Bad Request"

put:
  summary: "Start Deployment"
  description: |
    Deploy your Elastigroup (triggers Blue/Green Deployment that replaces the existing instances in the Elastigroup).\
    Note: If configured with health check, the grace period will be ignored
  operationId: "elastigroupAwsDeploy"
  tags:
    - "Elastigroup AWS"
  parameters:
    - $ref: "../../../../commons/parameters/groupId.yaml"
    - in: "query"
      name: "accountId"
      example: "act-123abc"
      description: >
        ID of the account associated with your token
      schema:
        type: "string"
      required: false
  requestBody:
    required: true
    content:
      application/json:
        schema:
          allOf:
            - $ref: "../schemas/start-deployment.yaml"
  responses:
    200:
      $ref: "../responses/elastigroup-deployment-status-example2.yaml"
    400:
      description: "Bad Request"
