title: ITF Static Target Group Configuration
type: object
description: |
  Contains the configuration details of an ITF static target group.
required:
  - arn
  - percentage
properties:
  arn:
    type: string
    description: |
      Identifier of the target group in AWS.
    example: "arn:aws:elasticloadbalancing:us-west-2:123456789012:targetgroup/blue-targets/73e2d6bc24d8a067"
  percentage:
    type: number
    description: |
      A float number in the range of 0.1-10.
    example: 0.4