type: object
title: Security
properties:
  containerImage:
    type: object
    properties:
      approvedImages:
        type: array
        description: Set list of permitted repositories for container images.
        items:
          type: string
          example:
            - "gce.io/*"
            - "docker.*"
