type: object
title: shielded-instance-config
description: >
  The Ocean shielded instance configuration object.
properties:
  enableSecureBoot:
    type: boolean
    description: >
      Enable the secure boot parameter on the GCP instances.
    example: true
  enableIntegrityMonitoring:
    type: boolean
    description: >
      Enable the integrity monitoring parameter on the GCP instances.
    example: true
