type: object
title: Application Object
description: Application for Amazon EMR to install and configure when launching the cluster
properties:
  name:
    type: string
    description: Application name
    example: Hue
  args:
    type: array
    description: Application arguments
    items:
      type: string
  version:
    type: string
    description: Application version
    example: '1.0'
