type: object
properties:
  groupId:
    type: string
    description: Group ID
    example: sig-1b656b92
  rollId:
    type: string
    description: Roll ID
    example: sbgd-aafb7671
  actionType:
    type: string
    description: Roll ID
    example: DETACH_NEW
  detachedInstances:
    type: string
    example:
      - i-0b6974ad592f8d9ba
