type: object
title: spotinst:aws:ec2:group:roll:action
properties:
  actionType:
    type: string
    title: Type of action
    description: >
      Sets the action that will take place, Accepted values are: DETACH_OLD,
      DETACH_NEW
    example: DETACH_NEW
  shouldHandleAllBatches:
    type: boolean
    title: Should Hnadle All Batches Criteria
    example: true
    default: false
    description: >
      Indicator if the action should apply to all batches of the deployment or
      only the latest batch
  drainingTimeout:
    type: integer
    title: Draining timeout criteria
    description: |
      Indicates (in seconds) the timeout to wait until instance are detached
    example: 200
  shouldDecrementTargetCapacity:
    type: boolean
    title: Should Decrement Target Capacity criteria
    example: true
    default: true
