type: object
title: EBS Configuration Object
description: >
  Information about the EBS configurations that will be attached to each EC2
  instance in the group.
required:
  - ebsBlockDeviceConfigs
  - ebsOptimized
properties:
  ebsBlockDeviceConfigs:
    type: array
    description: >-
      An array of Amazon EBS volume specifications attached to a cluster
      instance.
    items:
      $ref: ./ebsBlockDeviceConfig.yaml
  ebsOptimized:
    type: boolean
    description: Indicates whether an Amazon EBS volume is EBS-optimized.
    example: true
