type: object
properties:
  id:
    type: string
    title: ID
    example: sbgd-781c6212
  status:
    type: string
    title: Status
    example: starting
  progress:
    type: object
    properties:
      unit:
        type: string
        title: Unit
        example: percent
      value:
        type: integer
        title: Value
        example: 0
  createdAt:
    type: string
    title: Created At
    example: 2018-03-27T19:50:12.000+0000
  updatedAt:
    type: string
    title: Updated At
    example: 2018-03-27T19:50:16.000+0000
