type: object
properties:
  id:
    type: string
    title: ID
    example: sbgd-cc4c44e2
  status:
    type: string
    title: Status
    example: finished
  progress:
    type: object
    properties:
      unit:
        type: string
        title: Unit
        example: percent
      value:
        type: integer
        title: Value
        example: 100
  createdAt:
    type: string
    title: Created At
    example: 2018-03-26T19:22:45.000+0000
  updatedAt:
    type: string
    title: Updated At
    example: 2018-03-26T19:26:17.000+0000
