type: object
properties:
  id:
    type: string
    title: ID
    example: sbgd-3ee19606
  status:
    type: string
    title: Status
    example: stopped
  progress:
    type: object
    properties:
      unit:
        type: string
        title: Unit
        example: percent
      value:
        type: integer
        title: Value
        example: 0
  createdAt:
    type: string
    title: Created At
    example: 2018-03-27T19:35:41.000+0000
  updatedAt:
    type: string
    title: Updated At
    example: 2018-03-27T19:39:18.000+0000
