type: object
title: Nested Configuration Object
properties:
  classification:
    type: string
    description: The grouping within a configuration.
    example: hadoop-env
  properties:
    type: object
    description: >
      Within a configuration classification, a set of properties that represent
      the settings that you want to change in the configuration file. Duplicates
      not allowed.
    example:
      HADOOP_DATANODE_HEAPSIZE: 2048
      HADOOP_NAMENODE_OPTS: '-XX:GCTimeRatio=19'
