summary: Ocean CD
post:
  summary: "Create Ocean CD Environment"
  description: |
    Create Ocean CD Environment entity.
  operationId: "OceanCDEnvironmentCreate"
  tags:
    - "Ocean CD"
  requestBody:
    required: true
    content:
      application/json:
        schema:
          allOf:
            - $ref: "../schemas/oceanCDEnvRequest.yaml"
  responses:
    200:
      $ref: "../responses/oceanCDEnvResponse.yaml"
    400:
      description: "Bad Request"
get:
  summary: "List Ocean CD Environments"
  description: >
    List all Ocean CD environments.
  operationId: "OceanCDEnvironmentList"
  tags:
    - "Ocean CD"
  responses:
    200:
      $ref: "../responses/oceanCDEnvResponse.yaml"
    400:
      description: "Bad Request"
